### ISSUE TITLE
Feature Request: onExportODT

### ISSUE THREAD

**Issue by andyboeh** [gturri/hidden#37]
I need to suppress certain links of a page in the ODT export. Initially, I thought about adding this to the odt plugin, when I discovered this plugin. For dw2pdf, this mode has been implemented and works properly.

Could this be extended to an onExportODT functionality?

Thanks

**Comment by gturri** [comment]
As far as I remember, the only thing we do with pdf, is to add the an onExportPdf option to override the header, but we display everything.

(On the other hand, the odt plugin has already its own special treatment (https://github.com/gturri/hidden/blob/660a5bf7981fc90bfcabbc967428341a4f1310b8/syntax.php#L232), to ensure the text isn't hidden.)

If I understand correctly, we could add a new option (for instance <hidden -hiddenOnExport>) so that those blocks are completely not displayed when they're exported. Is it correct?
(in particular, in your mind, should the header be exported ("click to display"), or should it be removed?)

**Comment by gturri** [comment]
Closing because the additional info needed to move on with this feature request (cf question in the previous comment) is still missing after 2 years
