### ISSUE TITLE
Doesn't work within lists

### ISSUE THREAD

**Issue by JojoSc** [gturri/hidden#54]
The following code doesn't produce a hidden section, instead everything (including the <hidden> tags) is visible in the list:

```
  * This isn't hidden:
  * <hidden Test>test</hidden>
```

When removing `Test`nothing shows at all.

**Comment by gturri** [comment]
I'm afraid it's because of the way Dokuwiki defines list: on https://github.com/splitbrain/dokuwiki/blob/bc42db0f26c729b8d03590eb112af4d76c617d9a/inc/parser/parser.php#L479 we see that lists only allow 4 other types of mode inside it, and that it's not possible to include a [`container` mode](https://github.com/gturri/hidden/blob/master/syntax.php#L20).

As a workaround you might want to try changing the definition of list by changing the sources of your Dokuwiki, but I'm not sure it can work properly
