### ISSUE TITLE
hidden plugin inconsistently working with recent DokuWiki upgrade, including RC2

### ISSUE THREAD

**Issue by andylynchpe** [gturri/hidden#59]
I have pages which utilize the hidden plugin. On maybe 90% of my pages, it works correctly, but the remainder will randomly display all of the text that's supposed to be hidden.

Refreshing does not fix it (including shift or ctrl + F5).

If I edit the page in any way and save it, then the hidden plugin will work as expected again, but eventually the page may revert to displaying the full contents of the hidden text.

Edit: In case it's important, all of my hidden text is enclosed in nowiki tags. The nowiki functionality is working as expected.

**Comment by Klap-in** [comment]
Maybe you can create a small as possible example of syntax that still reproduces this case?

**Comment by gturri** [comment]
Thanks for the suggestion Klap-in: it will indeed be hard to work on that issue if it's not possible to reproduce it.

Also, this plugin relies on javascript so it may be broken by other plugins or template which may add some slightly corrupted JS.

It would hence be awesome if you can:

- disable all your other plugins
- switch back to the default Dokuwiki template and disable all other template
- check if the issue is still there

**Comment by andylynchpe** [comment]
I have not been able to reproduce this since disabling and then re-enabling all of my extensions. If this begins to occur again and I am able to identify a conflicting plugin or some other reproducible cause, I will open a new issue. Thank you for your input.
