### ISSUE TITLE
Compatibility with rc2020-06-01 Hogfather

### ISSUE THREAD

**Issue by urusha** [gturri/hidden#60]
This plugin doesn't seem to work with rc2020-06-01 "Hogfather" dokuwiki release.

**Comment by gturri** [comment]
Thank you for this bug report.
I tested against this version a couple weeks ago and I had the feeling that it worked. Could you please be more specific on what seems to not work?
(also, please, disable all other plugins and custom templates you might have, and empty both the cache of your browser and the cache of your instance of Dokuwiki, since it might interfere with this plugin)

**Comment by urusha** [comment]
![image](https://user-images.githubusercontent.com/1746504/88664276-84a95700-d0e5-11ea-92d8-8694920cbad2.png)
I've just updated the installation, removed `data/cache/*` directories, touched `conf/local.php` and cleared browser cache. As you see, the content is not hidden by default and nothing happens on click.
Plugin version: 2019-03-31

**Comment by gturri** [comment]
I'm afraid I'm not able to reproduce the issue (I've just tested with the
latest available version of dokuwiki, ie: rc-2020-06-09 ) so I'm going to
need more information.
Actually the issue you're experiencing looks like a javascript issue. It
would be awesome if you can open the developer tools of your browser (press
F12 on firefox), go to the "console" tab, and tell me if there are errors
when you load the page (or when you click on the "click to hide" text).
Also, please deactivate all your other plugins, and switch to the default
template (because add-ons may break the javascript)

**Comment by urusha** [comment]
That was a problem with `dtable` plugin actually. Thanks for attention and sorry for the noise.
