### ISSUE TITLE
Handling of "must be run within Dokuwiki"

### ISSUE THREAD

**Issue by erik-alm** [gturri/hidden#62]
I may be wrong, but it seems this plugin has some issues with being possible to be run from outside of Dokuwiki?

Should the following code (or even more rows)…

```php
if(!defined('DOKU_INC')) define('DOKU_INC',realpath(dirname(__FILE__).'/../../').'/');
```

…be replaced with:

```php
// must be run within Dokuwiki
if (!defined('DOKU_INC')) {
    die();
}
```

Or, am I kicking a dead horse?

**Comment by gturri** [comment]
Thanks for this bug report.

I just had a look at some plugins maintained by the dokufreaks team (in my understanding they should be knowledgeable about what the good pratices are), and it seems that you are correct. I'll try to take the time to do a patch and test it in a not too distant future.

**Comment by erik-alm** [comment]
Thanks for the quick, inspiring reply.

Taking a look through what I have installed I can see...

...same problem as above:

- definitionlist
- gallery
- orphanswanted
- snippets

...no checks at all (unless this is checked someplace else, or perhaps the plugin fails if the DOKU_INC variable is not set?):

- backlinks
- discussion (uses two syntax files in a syntax folder, neither has a check)
- pagelist
- tag
- talkpage
- wrap

So more than half of my installed plugins...

**Comment by gturri** [comment]
> I guess I should create issues? Or?

I don't know.
As far as this `hidden` plugin is concerned, it's fixed since yesterday. For the other plugins I'm not sure to which extent it is that important (in the sense that I'm not sure I understand the risk if a user browse directly to a plugin file. I mean: I expect such query would display nothing and do nothing most of the time anyway).

I guess that if you're motivated you can still try to open bug reports (or, even better, pull requests) for those other plugins. But perhaps you might also want to not spend to much time on that either.
